### ISSUE TITLE
Which version is supports for Angular V13 app?

### ISSUE THREAD

**Issue by vdnprasad** [domi92/ngx-touch-virtual-keyboard#6]
Which version is supports for Angular V13 app? If I'm using your package latest version I'm getting an error.

**Comment by domi92** [comment]
Supported version starts from ^14.
There should not be problems to add also version 13, but I must check it. I choose to start library including only one version with LONG TERM SUPPORT expired (version 14 LTS expired 18 Nov 2023).
Let me know if is really and issue and can't update your app
